on:
  push:
    branches:
      - master
  release:
    types:
      - created


name: Deploy
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: clean
        run:  make clean
      - name: install
        run:  make install
      - name: build & test & publish
        run:  xvfb-run -a --server-args='-screen 0 1280x800x24 -ac -nolisten tcp -dpi 96 +extension RANDR' make pre-publish
      - name: Publish
        uses: menduz/oddish-action@master
        with:
          cwd: ./packages/ulla-ecs
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Publish
        uses: menduz/oddish-action@master
        with:
          cwd: ./packages/ulla-compiler
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Publish
        uses: menduz/oddish-action@master
        with:
          cwd: ./packages/ulla-rpc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Publish
        uses: menduz/oddish-action@master
        with:
          cwd: ./packages/ulla-builder
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}