on:
  push:
    branches:
      - master

name: Deploy
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: clean
        run:  make clean
      - name: install
        run:  make install
      - name: build
        run:  make build
      - name: examples & tests
        run:  make example
      - name: publish
        run:  make publish