on:
  push:
    branches:
      - master

name: Deploy
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: clean
        run:  make clean
      - name: install
        run:  make install
      - name: npm login
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc
      - name: build & test & publish
        run:  make publish